name: Build and Deploy code

on: 
  push: 
    branches: 
      - 'main'

jobs:
  build: 
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: admin123
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: 25d0b1a69ad2b9ea4cc76564200ae1b771bd5deded93a761c5b8668aede229bd
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.8.9'
      - name: update pip
        run: python -m pip install --upgrade pip 
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: | 
          pip install pytest
          pytest 


